# Define all the Social Auth Keys Here

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '75supyh5c3vp4a'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'MueyC1hce9le6544'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
